### ISSUE TITLE
Hurl Settings (post-release planning)

### ISSUE THREAD

**Issue by U-C-S** [U-C-S/Hurl#149]
continues #21

## Features
- [ ] Add Help links in the bottom of page?
- [ ] Better Rule Testing
- [ ] Edit Browsers

#### In Future
- [ ] Logs/History of opened links (including Rules)

## Dev stuff
- [ ] Custom styles for commonly used control styling properties
- [ ] Bind BackgroudType to a Enum
