### ISSUE TITLE
Hurl Settings App

### ISSUE THREAD

**Issue by U-C-S** [U-C-S/Hurl#21]
## TODO
for alpha release
- [x] Update the UI for Rulesets List
- [x] Plan where to put the Test Rules feat
- [x] Impl Move up/down and delete ruleset
- [ ] Phase out Ruleset Manager
- [x] Proper spacing hierarchy

For stable release
- [x] Support Launch args to open Settings/Rulesets page directly
- [x] Have a Home/About page
- [x] Support Listing browsers in Browser Page, Editing Browser for post stable release
- [x] Error handling and Form validations
- [x] Implement view rules

Post release
- [ ] Add Help links in the bottom of page?
- [ ] Better Rule Testing
- [ ] Custom styles for commonly used control styling properties
- [ ] Bind BackgroudType to a Enum
- [ ] Edit Browsers

## In Future
- [ ] Logs/History of opened links (including Rules)

**Comment by U-C-S** [comment]
![image](https://user-images.githubusercontent.com/50218121/153749772-90b3a36e-659d-4e13-900a-0e66195b72a4.png)
RA uses 1.4GB RAM

**Comment by U-C-S** [comment]
Ruleset Manager
- [ ] Decide about Info Btn
- [ ] Remove dependency on `Hurl.Library.SettingsFile`
- [ ] Keep the Ruleset Accordion open when moving it up and down

**Comment by Jay-o-Way** [comment]
My idea: would be nice if all the pages can live in one app window, with a compact Navigation (possibly on the left).

**Comment by U-C-S** [comment]
Yesss.... Want to do something like that.

Need to experiment with how pages work in WPF
