### ISSUE TITLE
🚀 Maybe a ROADMAP 🚀

### ISSUE THREAD

**Issue by U-C-S** [U-C-S/Hurl#41]
Currently (v0.6.1), For me, the Hurl is almost feature complete or fitting for all of my use cases apart from few features listed below...
- [ ] Proper Communication with Hurl Browser Extension 
- [ ] Context menu option `Open this browser for next 10mins automatically`
- [ ] Better Icon retrieval methods (currently, Icons are taken at runtime from browser exe files)
- [ ] Even faster startup (I believe porting Hurl to C++ is my best option here)
- [ ] Keyboard Support

Additionally, Keeping me aside, For Hurl to be properly useful for all of its users, I believe for most, the following are necessary...
- [ ] Hurl Settings GUI
- [ ] OOBE
- [ ] Fetching Browser profiles automatically
- [ ] History upto 10 items
- [ ] Automatic Rules to open a certain browser for certain links (Might have a performance impact)

I intend to work on those for next few months slowly with spending a week per month (might even less, as my university exams approach).

**Comment by mix3d** [comment]
That last one, automatic rules, is what I was looking for in a Windows alternative to Velja or Choosey. Anything I can help with there?

**Comment by riotrah** [comment]
Echoing @mix3d, I also came here looking for Choosey, browserosaurus and Velja windows alternatives. 

I'm trying to port browserosaurus to windows but I have literally no clue how to enable an (electron) app to register itself as a browser, so I'd be happy to divert time to this instead, though I have no C# experience, and my last time doing OOP was like ~2 years ago. Still, this project is so promising and great already that I'm very excited about it. Thanks @U-C-S !

**Comment by U-C-S** [comment]
Thanks for the appreciation. Hurl is my experiment ground to learn about C#, .NET, Windows App dev, OSS... and other stuff. I still have long way to go, but I came a long way too.
